### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by edvilme** [hackclub/hackclub.es#2]
Hello, I noticed this is a wip for some time and would like to contribute. Is contribution to this repo done through pull request or directly?

Greetings

**Comment by lachlanjc** [comment]
Hey @edvilme! We’d absolutely love PRs with updates here, thank you :)

**Comment by edvilme** [comment]
Ok, I see two alternatives, but don´t know how the site is built. I could try forking hackclub.com website source in here and then translating, or trying to do it manually, Either way, I understand the components are built using react, am I right? Just so I know what I will be doing...

**Comment by lachlanjc** [comment]
@edvilme We’d actually prefer not doing that. (& the existing website is about to be wholly rewritten.) Unfortunately we don’t have the capacity to continuously translate all our text, so we’d like internationalized sites for Hack Club to be wholly separate. Since this site is super simple, I’m fine keeping it static HTML + CSS, but we’d absolutely love if community members could add content to this/other language sites!

**Comment by edvilme** [comment]
Sorry forgot to reply. Will do when I have time (somehow school work is more intense now lol). Also, happy birthday!

**Comment by lachlanjc** [comment]
Thanks! No rush, just make a PR when you’re ready! If you do want to add some more text/content, go for it, & I can add some design polish.

**Comment by edvilme** [comment]
Little late, but just made PR :D @lachlanjc

**Comment by lachlanjc** [comment]
Sorry for the delay you'll have here. Hack Club staff is taking a little break for the next week, so I will review this & get back to you the week of the 17th. Thanks so much!
